version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-attendance
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: attendance_db
      MYSQL_USER: attendance_user
      MYSQL_PASSWORD: attendance_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: yourdockerhubusername/student-attendance-tracker:latest
    container_name: springboot-attendance-app
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/attendance_db
      SPRING_DATASOURCE_USERNAME: attendance_user
      SPRING_DATASOURCE_PASSWORD: attendance_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always

volumes:
  db_data:
